// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS0dHFaJITw1xVP1vb7iUJpdYMyKDEQSU',
    appId: '1:456316594497:web:6fef98e322c9309fcc99c0',
    messagingSenderId: '456316594497',
    projectId: 'crudtutorial-8805e',
    authDomain: 'crudtutorial-8805e.firebaseapp.com',
    storageBucket: 'crudtutorial-8805e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwdrrH1VuNG-LMCYnpy5YtsGtzA6G4_IM',
    appId: '1:456316594497:android:c470b04aec84cfc3cc99c0',
    messagingSenderId: '456316594497',
    projectId: 'crudtutorial-8805e',
    storageBucket: 'crudtutorial-8805e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjJ6IiZM5io2lC6V9oAgTXB_1pl81DYME',
    appId: '1:456316594497:ios:b5f09e5f713f663ccc99c0',
    messagingSenderId: '456316594497',
    projectId: 'crudtutorial-8805e',
    storageBucket: 'crudtutorial-8805e.appspot.com',
    iosBundleId: 'com.example.simpleCrudFirebase',
  );
}
